commitizen:
  name: cz_github_jira_conventional
  tag_format: v$version
  version: 0.0.1
  jira_prefix: XX-
  jira_base_url: https://myproject.atlassian.net
  github_repo: brianburwell11/cz-github-jira-conventional-footer
  